### ISSUE TITLE
Missing image in under "Jetzt Vormerken"

### ISSUE THREAD

**Issue by betatim** [BlockSigner/cove#23]
The page looks 😍!

There is a missing image next to the text "Mit qualifizierter elektronischer Signatur (QES) von Swisscom AG" when visiting https://skribble.netlify.com/de/

<img width="1024" alt="screen shot 2019-03-05 at 11 41 03" src="https://user-images.githubusercontent.com/1448859/53799824-9bbd3700-3f3b-11e9-902e-df95e5548034.png">

Firefox 66.0b10 (64-bit) on OSX.

**Comment by betatim** [comment]
When I visit https://skribble.netlify.com/ a different image ends up missing :-/

<img width="949" alt="screen shot 2019-03-05 at 11 44 50" src="https://user-images.githubusercontent.com/1448859/53800021-1e45f680-3f3c-11e9-870b-d629c40135f1.png">

**Comment by michelfernandez** [comment]
Funktioniert nun glaube ich.
